### ISSUE TITLE
asker file --no-output INPUTFILE

### ISSUE THREAD

**Issue by dvarrui** [teuton-software/asker#12]
The same functionality than "asker file INPUTFILE" but in this case we dont create output files.

**Comment by dvarrui** [comment]
What is this useful for?
Well for example if you want to simulate asker function without running it.
It isnt important buy it is nice. :-)

**Comment by dvarrui** [comment]
No body seems to need it...
so I close it
:-)

**Comment by fvarrui** [comment]
😞

**Comment by dvarrui** [comment]
I'm not sure but it seems you are not happy about closing this issue.
I'm thinking this issue is useful running some test.
