### ISSUE TITLE
Misspelled is misspelled :-D

### ISSUE THREAD

**Issue by ermengolbota** [teuton-software/asker#14]
The name of misspelled questions of type "d" miss an "s" (I think that is only with d2-def and d2-name)

- d1none-misspelled (good)
- d2def-mispelled (wrong)
- d2name-mispelled (wrong)
- d2false-misspelled (good)

Not a real problem, but just to let you know.

I've installed it over ubuntu 20.04 with 
sudo gem install asker-tool
and asker -v says
asker version 2.2.0

Thanks for your time!!

**Comment by dvarrui** [comment]
Try again! I think is solved now.
asker docs/example/acdc.haml it seems fine now!
Thank you very much!

Do you know Ruby? O like to know?
