### ISSUE TITLE
asker check doesn't detect wrong table definition in haml file

### ISSUE THREAD

**Issue by ermengolbota** [teuton-software/asker#15]
The table definition in haml files must not have spaces between **%table** and **{**

%table{ :fields => 'Contingut del fitxer' }

but if you insert an space

%table { :fields => 'Contingut del fitxer' }

then asker software generates an error like
_Illegal nesting: content can't be both given on the same line as %table and nested within it. (Haml::SyntaxError)_
but the check option of Asker says
$>asker check file.haml
Syntax OK!
$>

**Comment by dvarrui** [comment]
Now it is solved... but tables format has been updated to:
%table { fields: 'Contingut del fitxer' }

The old format is accepted but not checked.
