### ISSUE TITLE
b1match3x1 adds also a misspelled option

### ISSUE THREAD

**Issue by ermengolbota** [teuton-software/asker#16]
Asker generated a question of type **b1match3x1** where a wrong option is a misspelled version of a correct one (in my case the word "el" is replaced by "er").
I thought that **b1match3x1** didn't add misspelled options, that this was done by **b1match3x1misspelled**

**Comment by dvarrui** [comment]
I can't locate any problem! Sorry!

![b1match3x1misspelled-sample](https://user-images.githubusercontent.com/5159406/152180474-6fdeeeeb-a85f-4d60-a172-e987ab067843.png)

**Comment by dvarrui** [comment]
Another example with b1match3x1 question type:

There are 4 options ... and 5 answers... 1 of them,,, is useless.
The error answer is asociated to "rm..." that is a command no related with "rmdir" concept. 


![b1match3x1-sample](https://user-images.githubusercontent.com/5159406/152181534-70c4b60d-39e0-45e1-a8ea-b4a5532f4d7c.png)
