### ISSUE TITLE
Bajo número de preguntas de un sólo tipo

### ISSUE THREAD

**Issue by amarzar** [teuton-software/asker#20]
Quiero eliminar todos los tipos de preguntas salvo las `t8table`, el objetivo es generar sólo preguntas en las que los alumnos tengan que rellenar una respuesta corta  ¿porqué se obtienen un número bajo de preguntas de este tipo? ¿ de que depende esto ?

El archivo haml solo tiene una pregunta de tipo tabla y estoy usando `asker version 2.5.1`

```
%map{ lang: 'es', context: 'Comandos CISCO', version: '1'}
  
  %concept
    %names Comandos para la configuración de un router CISCO
    %tags modo, configuración, nombre, contraseña, consola, IP, máscara, interfaz, puerta, enlace
    %table{fields:'comando, descripción'}
      %row
        %col enable
        %col Entra en el modo privilegiado.
      %row
        %col show ?
        %col Muestra ayuda sobre los comandos disponibles.
      %row
        %col configure terminal
        %col Entra en el modo de configuración.
      %row
        %col hostname
        %col Cambia el nombre del equipo.
      %row
        %col no "comando"
        %col Desactiva un comando.
      %row
        %col logging console
        %col Activa o desactiva los mensajes de consola.
      %row
        %col copy running-config startup-config
        %col Guarda la configuración actual.
      %row
        %col reload
        %col Deshace los cambios hasta la última configuración guardada.
      %row
        %col show running-config
        %col Muestra la configuración actual del dispositivo.
      %row
        %col show ip interface brief
        %col Muestra la configuración de interfaces.
      %row
        %col show ip route
        %col Muestra la tabla de ruteo.
      %row
        %col show ip protocols
        %col Muestra los protocolos de ruteo activos y sus parámetros.
      %row
        %col configure terminal
        %col Entra en el modo de configuración.
      %row
        %col hostname
        %col Cambia el nombre del equipo.
      %row
        %col no logging console
        %col Detiene los mensajes de consola.
      %row
        %col line console 0
        %col Configura la consola.
      %row
        %col logging synchronous
        %col Configura la consola para que no interrumpa instrucciones o respuestas.
      %row
        %col exit
        %col Sube un nivel en la consola.
      %row
        %col end (o CTRL+Z)
        %col Sube al nivel inicial en la consola.
      %row
        %col enable password
        %col Configura la contraseña del modo privilegiado.
      %row
        %col enable secret
        %col Configura la contraseña encriptada del modo privilegiado.
```

![SCR-20230305-ssz](https://user-images.githubusercontent.com/58997290/222984881-61f49fa9-f9a0-47f6-a7e3-c38eae716cb6.png)

**Comment by dvarrui** [comment]
# Reproduciendo el problema

Las preguntas del tipo "t8table" tienen esta forma:

```
Comandos para la configuración de un router CISCO
Completa la siguiente asociación:
* Descripción: "Cambia el nombre del equipo."
* Comando: [*]
Escribir una palabra
```
En este ejemplo la respuesta correcta sería "hostname".

Por tanto, lo lógico sería pensar que se deberían generar tantas preguntas de este tipo como filas (rows) tiene la tabla (comando-descripción). Por tanto si el fichero de entrada tiene 21 filas, se deben generar 21 preguntas de este tipo y no 5 como está ocurriendo.

Este problema o bug lo tiene asker 2.5.1 y 2.5.9 (la versión actual).

Por tanto, está claro que debemos revisar el código encargado de generar las preguntas de este tipo. Según lo que veamos lo indicaremos por esta vía.

Muchas gracias @amarzar!

**Comment by amarzar** [comment]
Genial ¡¡¡ Han pensado en una opción para el archivo `ini`  que complemente a `exclude` y  que permita seleccionar que se genere un único  tipo de pregunta/s, por ejemplo  `only = t8table` o `only = t8table, code1`

**Comment by dvarrui** [comment]
Buena idea!
Lo apuntamos!

**Comment by dvarrui** [comment]
# Salida correcta

Tras analizar el código se concluye que el resultado es correcto, pero claro esto merece una explicación.

- El tipo de pregunta **t8table** genera preguntas de respuesta corta únicamente cuando la respuesta es **1 palabra**.
- El tipo de pregunta **t9table** genera preguntas de respuesta corta únicamente cuando la respuesta son **2 palabras**.

# Generar más preguntas?

En teoría es posible cambiar el código de Asker para generar preguntas de respuesta corta donde la respuesta sea un número indeterminado de palabras. Se tomó la decisión de no hacerlo así porque cuantas más palabras incluya la respuesta es posible que existan multitud de soluciones válidas que sería casi imposible reflejar en el input de entrada.

El objetivo de asker es generar preguntar que se puedan corregir automáticamente y para ello es necesario que dichas preguntas sean lo más "cerradas" posible. (Aún así asker tiene un % de error a la hora de generar las preguntas con errores)

En cualquier caso, esta decisión de funcionamiento se podría debatir si se  considera necesario.

**Comment by amarzar** [comment]
Perfecto, tiene todo el sentido que sea así. Gracias
